name: uploadReleaseToS3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Generate script and config lists
        run: |
          # Create a directory for metadata
          mkdir -p metadata

          # Generate list of Lua scripts with full paths
          echo "Generating list of Lua scripts..."
          find . -type f -name "*.lua" -not -path "*/\.*" | sed 's|^./||' > metadata/scripts.list

          # Generate list of conf files with full paths
          echo "Generating list of conf files..."
          find ./conf -type f -name "*.conf" -not -path "*/\.*" | sed 's|^./||' > metadata/configs.list

          # Verify that files exist
          echo "Found $(wc -l < metadata/scripts.list) script files"
          echo "Found $(wc -l < metadata/configs.list) config files"

          # Create a JSON file with both lists for easier parsing in Lua
          # Using simple echo commands instead of heredoc for better YAML compatibility
          echo "{" > metadata/available_files.json
          echo "  \"scripts\": [" >> metadata/available_files.json
          sed 's/^/    "/;s/$/",/' metadata/scripts.list | sed '$s/,$//' >> metadata/available_files.json
          echo "  ]," >> metadata/available_files.json
          echo "  \"configs\": [" >> metadata/available_files.json
          sed 's/^/    "/;s/$/",/' metadata/configs.list | sed '$s/,$//' >> metadata/available_files.json
          echo "  ]" >> metadata/available_files.json
          echo "}" >> metadata/available_files.json

          # Verify JSON is valid
          cat metadata/available_files.json
        shell: bash

      - name: Upload Lua files and metadata to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT_URL: https://s3.7thseraph.org
          MINIO_S3_BUCKET: wiki.avakot.org
          TARGET_DIR: oreo.temp
        run: |
          set -e
          SOURCE_PATH="." # Source is the root of the repository
          S3_TARGET_PATH="s3://${MINIO_S3_BUCKET}/${TARGET_DIR}/"

          echo "Uploading .lua files from ${SOURCE_PATH} to ${S3_TARGET_PATH}"

          # Upload .lua files
          aws s3 cp "${SOURCE_PATH}" "${S3_TARGET_PATH}" \
            --recursive \
            --exclude "*" \
            --include "*.lua" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}

          # Upload conf directory and its contents
          if [ -d "${SOURCE_PATH}/conf" ]; then
            echo "Uploading conf/ directory..."
            aws s3 cp "${SOURCE_PATH}/conf" "${S3_TARGET_PATH}conf" \
              --recursive \
              --endpoint-url ${AWS_S3_ENDPOINT_URL}
          else
            echo "conf/ directory not found. Skipping."
          fi

          # Upload metadata files
          echo "Uploading metadata files..."
          aws s3 cp "metadata/available_files.json" "${S3_TARGET_PATH}available_files.json" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}
          aws s3 cp "metadata/scripts.list" "${S3_TARGET_PATH}scripts.list" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}
          aws s3 cp "metadata/configs.list" "${S3_TARGET_PATH}configs.list" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}

          echo "Upload complete."
        shell: bash
