name: uploadReleaseToS3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Upload Lua files and conf directory to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT_URL: https://s3.7thseraph.org
          MINIO_S3_BUCKET: wiki.avakot.org
          TARGET_DIR: oreo.temp
        run: |
          set -e
          SOURCE_PATH="." # Source is the root of the repository
          S3_TARGET_PATH="s3://${MINIO_S3_BUCKET}/${TARGET_DIR}/"

          echo "Uploading .lua files and conf/ directory from ${SOURCE_PATH} to ${S3_TARGET_PATH}"

          # First, upload .lua files
          aws s3 cp "${SOURCE_PATH}" "${S3_TARGET_PATH}" \
            --recursive \
            --exclude "*" \
            --include "*.lua" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}

          # Then, upload conf directory and its contents
          if [ -d "${SOURCE_PATH}/conf" ]; then
            echo "Uploading conf/ directory..."
            aws s3 cp "${SOURCE_PATH}/conf" "${S3_TARGET_PATH}conf" \
              --recursive \
              --endpoint-url ${AWS_S3_ENDPOINT_URL}
          else
            echo "conf/ directory not found. Skipping."
          fi

          echo "Upload complete."
        shell: bash
