name: uploadReleaseToS3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Upload Lua files to S3 # Renamed step
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT_URL: https://s3.7thseraph.org
          MINIO_S3_BUCKET: wiki.avakot.org
          TARGET_DIR: oreo.temp
          # RELEASE_TAG is removed as it's not used in the updated S3 path or command
        run: |
          set -e
          SOURCE_PATH="." # Source is the root of the repository
          # S3_TARGET_PATH uploads to the root of the TARGET_DIR
          S3_TARGET_PATH="s3://${MINIO_S3_BUCKET}/${TARGET_DIR}/"

          echo "Uploading .lua files from ${SOURCE_PATH} to ${S3_TARGET_PATH}"

          # Recursively copy only .lua files from the source path to S3
          # Exclude all files first, then include .lua files.
          # Add specific directory/file exclusions as needed.
          aws s3 cp "${SOURCE_PATH}" "${S3_TARGET_PATH}" \
            --recursive \
            --exclude "*" \
            --include "*.lua" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --endpoint-url ${AWS_S3_ENDPOINT_URL}

          echo "Lua files upload complete."
        shell: bash
